name: kweli_agents_fe
description: A new Flutter project.

publish_to: "none"
version: 99.99.99+99

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Apple
  cupertino_icons: ^1.0.2
  # Provider
  provider: ^6.0.1
  # Fonts
  google_fonts: ^2.1.0
  ############
  # Firebase #
  ############
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.0
  cloud_firestore: ^3.1.1
  # Spinkit
  flutter_spinkit: ^5.1.0
  # Svg
  flutter_svg: ^1.0.0
  # Geolocator
  geolocator: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/launchers/
    - assets/logos/
    - assets/icons/
