name: Build and Release
on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # In-line replacement
      - name: Update app version in YAML
        run: sed -i 's/99.99.99+99/1.0.${{ github.run_number }}+${{ github.run_number }}/g' pubspec.yaml

      - name: Update firebase project id
        run: sed -i 's/#{PROJECT_ID}#/${{ secrets.PROJECT_ID }}/g' .firebaserc

      # Clean Build
      - run: flutter clean

      # Fresh packages
      - run: flutter pub get

      # Build
      - run: flutter build apk --shrink --target-platform android-arm

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          commit: main
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
          tag: v1.0.${{ github.run_number }}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: admin
          releaseNotesFile: distribution/whatsnew/whatsnew-en-US
          file: build/app/outputs/apk/release/app-release.apk
